name: Campaigns

on:
  workflow_dispatch:
    inputs:
      environmentName:
        type: choice
        description: 'Environment name'
        required: true
        options:
        - net
        - com

jobs:
  campaigns-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1 ]
    steps:
      - name: Setting env variables 'com' environment
        if: ${{ github.event.inputs.environmentName == 'com' || github.event_name == 'schedule' }}
        run: |
          echo "CONFIG_FILE_NAME=./config/com.json" >> $GITHUB_ENV
          echo "CYPRESS_KEY=${{ secrets.CYPRESS_RECORD_KEY_COM }}" >> $GITHUB_ENV

      - name: Setting env varibles 'net' environment
        if: ${{ github.event.inputs.environmentName == 'net' }}
        run: |
          echo "CONFIG_FILE_NAME=./config/net.json" >> $GITHUB_ENV
          echo "CYPRESS_KEY=${{ secrets.CYPRESS_RECORD_KEY_NET }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache node modules and cypress
        uses: pat-s/always-upload-cache@v3.0.1
        id: automation-cache
        with:
          path: |
            **/node_modules
            cypress/cache
            /home/runner/.cache/Cypress
            /home/runner/.cache/Cypress/9.6.1
          key: automation-cache-${{ hashFiles('./package-lock.json') }}
      - name: "Install dependencies"
        if: steps.automation-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 45
        with:
          parallel: false
          working-directory: ./
          spec: |
            ./cypress/integration/tests/campaigns/*.feature
          browser: chrome
          headless: true
          record: true
          config-file: ${{ env.CONFIG_FILE_NAME }}
          env: CYPRESS_MAILOSAUR_API_KEY=${{ env.CYPRESS_MAILOSAUR_API_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ env.CYPRESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
