name: Client Admin Tests

on:
  #schedule:
    # Runs on Tue,Fri
    #- cron: '0 0 * * 2,5'
  workflow_dispatch:
    inputs:
      environmentName:
        type: choice
        description: 'Environment name'
        required: true
        options:
        - net
        - com

jobs:
  client-admin-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2 ]
    steps:
      - name: Setting env variables 'com' environment
        if: ${{ github.event.inputs.environmentName == 'com' || github.event_name == 'schedule' }}
        run: |
          echo "BASE_URL=https://admin.plaidbean.com/" >> $GITHUB_ENV
          echo "MESSAGE_API_DOMAIN=https://ai.plaidbean.com/" >> $GITHUB_ENV
          echo "GRAPHQL_URL=https://gql.plaidbean.com/" >> $GITHUB_ENV
          echo "DRUPAL_URL=https://cms.plaidbean.com/" >> $GITHUB_ENV
          echo "PROVISION_NUMBER=(513) 647-2774" >> $GITHUB_ENV

      - name: Setting env varibles 'net' environment
        if: ${{ github.event.inputs.environmentName == 'net' }}
        run: |
          echo "BASE_URL=https://admin.plaidbean.net/" >> $GITHUB_ENV
          echo "MESSAGE_API_DOMAIN=https://ai.plaidbean.net/" >> $GITHUB_ENV
          echo "GRAPHQL_URL=https://ai.plaidbean.net/" >> $GITHUB_ENV
          echo "DRUPAL_URL=https://cms.plaidbean.net/" >> $GITHUB_ENV
          echo "PROVISION_NUMBER=(513) 854-4802" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache node modules and cypress
        uses: pat-s/always-upload-cache@v3.0.1
        id: automation-cache
        with:
          path: |
            **/node_modules
            cypress/cache
            /home/runner/.cache/Cypress
            /home/runner/.cache/Cypress/9.6.1
          key: automation-cache-${{ hashFiles('./package-lock.json') }}
      - name: "Install dependencies"
        if: steps.automation-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 40
        with:
          parallel: true
          working-directory: ./
          spec: |
            ./cypress/integration/tests/*/*.feature
          browser: chrome
          headless: true
          record: true
          config-file: ./cypress.json
          config: baseUrl=${{ env.BASE_URL }}
          env: MESSAGE_API_DOMAIN=${{ env.MESSAGE_API_DOMAIN }},GRAPHQL_URL=${{ env.GRAPHQL_URL }},DRUPAL_URL=${{ env.DRUPAL_URL }},CYPRESS_MAILOSAUR_API_KEY=${{ env.CYPRESS_MAILOSAUR_API_KEY }},PROVISION_NUMBER=${{ env.PROVISION_NUMBER }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
